services:

  database:
    ports:
      - "127.0.0.1:5432:5432"
  
  redis:
    ports:
     - "127.0.0.1:6379:6379"

  prometheus:
    ports:
      - "127.0.0.1:9090:9090"
    extra_hosts:
      - "backend:host-gateway"

  grafana:
    ports:
      - "127.0.0.1:3030:3030"