services:

  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./infra/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - frontend
      - backend
    networks:
      - ticketing-network

  frontend:
    image: jwchoi42/ticketing-frontend:latest
    restart: always
    depends_on:
      - backend
    networks:
      - ticketing-network
      
  backend:
    image: jwchoi42/ticketing-backend:latest
    restart: always
    depends_on:
      - database
      - redis
    
    environment:
    
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/ticketing_database
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}

      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
    
    networks:
      - ticketing-network

  database:
    restart: always
    ports:
      - "5432:5432"

  redis:
    restart: always

  prometheus:
    depends_on:
      - backend

  grafana:
    environment:
      GF_SERVER_ROOT_URL: "%(protocol)s://%(domain)s/grafana/"
      GF_SERVER_SERVE_FROM_SUB_PATH: true
